class Phrases {
    static phrases = [
        "Můj první pohlavní styk?<br />Co vám budu povídat, prostě %1!",
        "Celé noci nespím; může za to %1.",
        "Smrdí to tu jako %1.",
        "Problémů mám fůru,<br />ale %1 mě netrápí.",
        "Možná se tak narodila,<br />možná je to %1.",
        "Příští hračka v&nbsp;Happy Meal<br />bude %1.",
        "Když náhodou spím, sním.<br />V&nbsp;tom snu hraje hlavní roli %1.",
        "Dnešní děcka zajímá jen jedno:<br />%1U.",
        "Pomoc! Můj syn má %1!",
        "Tradiční čínská medicína tvrdí, že proti nachlazení je nejlepší %1.",
        "Oskara za %2<br />dostává %1.",
        "Poslouchejte! Zdá se mi, že slyším zpívat %2.",
        "Za můj poslední rozchod může<br />%1.",
        "V nové reality show na TV Barrandov bude v&nbsp;kleci šest medvědů a&nbsp;%1.",
        "Piju, abych zapomněl(a) na<br />%2.",
        "Paní učitelko, nemohl(a) jsem napsat domácí úkol.<br />Může za to %1.",
        "Batman miluje %2,<br />ale nikdy by to nepřiznal.",
        "Konec světa se blíží!<br />Způsobí ho %1!",
        "Většina dívek miluje %2.",
        "Zpřísnili prohlídky při vstupu na Pražský Hrad.<br />%1UC teď nesmí dovnitř.",
        "Až jednou umřu, bude za to moci<br />%1.",
        "Předvedu vám trik. Otevřu %2 a&nbsp;objeví se %1!",
        "Ovčáček poslal tweet na zásadní téma:<br />%1U.",
        "Na začátku bývá %1,<br />na konci je %1.",
        "Ať mi %1 pomáhá!",
        "Milá Sally,<br />pořebuji radu.<br />%1U<br />mi dělá čím dál tím větší starosti.",
        "Mikuláš teď prý dává zlobivým dětem místo uhlí %2.",
        "Úplně nejvíc moc je %1, víšjak.",
        "Až přestanou existovat peníze, univerzálním platidlem se stane %1.",
        "%1UC a&nbsp;%1C tvoří dokonalý pár!",
        "V&nbsp;novém Svěrákově filmu se zjistí, že %1C je ve skutečnosti %1.",
        'Romantická večeře se svíčkami není nic, když chybí %1.',
        'Kdo nemá %2, musí mít %1.',
        'Zavři oči a&nbsp;mysli na %2!',
        '%1U! Jednou to nikdy nestačí!',
        'Až bude svět řídit %1, poslední nadějí se stane %1.',
        'Násilí není řešení. Ale na %2 by fungovat mohlo.',
        'Během milování často myslím na %2.',
        'Rodiče se mi snažili zatajit, že existuje něco jako %1.',
        '%1U &mdash; na to mě vždycky dostanou do postele.',
        'V&nbsp;zajateckém táboře jsem vyměnil(a) %2 za 200 cigaret a&nbsp;libru krysího masa.',
        'Strýc byl v&nbsp;Mexiku. Přivezl si odtamtud %2, jinak nic.',
        'Můj masový pirožek obsahoval %2.',
        'Na cestu časem do minulosti si nezapomeň přibalit %2! Budou tě mít za mocného mága.',
        'Pozor na %2!<br />Je to past!',
        "Nový muzikál Daniela Hůlky se jmenuje %1U.",
        'Mezi SSSR a&nbsp;USA probíhal závod na Měsíc &ndash; u&nbsp;nás mezitím vyvinuli %2.',
        'Člověk v&nbsp;tísni dovezl obětem zemětřesení %2.',
        'Senát právě projednává ústavní zákon zakazující %2.<br />Osobně jsem proti.',
        'Plán na zbohatnutí je prostý:<br />1. %1U.<br />2. %1U.<br />3. Nekonečné zisky.',
        'Říkali, že nemám míchat %2C a&nbsp;%2.<br />Mýlili se.',
        'Ještě než vás zabiju, Bonde, musím vám ukázat %2.',
        '%1UC mi způsobuje nadměrnou plynatost.',
        'V&nbsp;Tatře vyvinuli nový náklaďák. Uveze %2C a&nbsp;spoustu dalších věcí.',
        'Hospodin se rozhněval a&nbsp;seslal na obě města %2.',
        'Mám tajnou superschopnost:<br />Umím se změnit na&nbsp;%2.',
        '%1UC stojí u&nbsp;počítače. Počítač říká ne.',
        '%1U? Ničeho není v&nbsp;nebi víc!',
        'Peklo je tam, kde je %1, ale chybí %1.',
        'Babička neměla ráda %2, ale uměla ocenit %2.',
        'Až když jsem viděl(a) %2, plně jsem pochopil(a) %2.',
        'Dětem uprchlíků bychom měli dopřát %2.',
        'Ve svém posledním prezidentském období se Václav Havel opíral zejména o&nbsp;%2.',
        'Polib mi %2!',
        'Co měl Miroslav Donutil k&nbsp;večeři?<br />No přece %2!',
        '%2UC je třeba vychutnat do poslední kapky.',
        'Za moji upocenost může %1.',
        '%1UC s&nbsp;časem zraje.',
        'Naštvané matky doporučují %2.<br />Vyzkoušejte na dětech a&nbsp;uvidíte sami!',
        '- Tatínku, proč maminka pláče?<br />- Inu, %1.<br />To bys taky plakal(a).',
        '%1UC prokazatelně motivuje děti k&nbsp;lepším studijním výkonům. Někdy stačí jen pohrozit.',
        'Brněnští vědci zjistili, že zprostředkujeme-li krysám %2, poklesne jejich sexuální výkonnost.',
        'Jakmile Slované přinesli do českých zemí %2, Keltové uznali, že je čas odejít.',
        'Témata k&nbsp;napsání krátké básničky:<br />&bull;&nbsp;%1<br />&bull;&nbsp;%1<br />Předveď se!',
        'Nevím, čím se bude bojovat ve 3.&nbsp;světové válce. Ale ve čtvrté to bude %1!',
        'Když zkusíš %2, bude tě bolet celé tělo.',
        'Přenechám %2. Nabídněte cenu.',
        'Marek Vašut často myslí na %2. Pak se snaží o&nbsp;tom vyprávět v&nbsp;rádiu.',
        'Institut Václava Klause bude vystavovat %2.',
        'Po zvolení budu rozvíjet %2.',
        'Do kin přichází nový film %1UC aneb Jak odstranit %2.',
        'Až vyhraju ve Sportce, nechám postavit sochu.<br />Svět nesmí zapomenout na %2.',
        'Když jsem zkoušel(a) LSD, %1C se mi před očima proměnil/a/o na %2.',
        'Zneškodnil(a) jsem %2.<br />A&nbsp;to jsem měl(a) jen odhodlání a&nbsp;%2.',
        'Jak to může dopadnout, když se dá dohromady %1C a&nbsp;%1?',
        'Na afterparty je nejlepší %1.<br />Většinou překoná i&nbsp;%2.',
        'Zničil jsem jsem %2, pánové. Šlo hlavně o&nbsp;%2.',
        '%2UC v&nbsp;pytli neutajíš.',
        'Tak dlouho se chodí pro %2, až se %1C utrhne.',
        'Co je zapotřebí, aby se %1 transformovalo v %2?',
        'Nemáš-li %2, nemůžeš vybudovat tržní ekonomiku.<br />To ti ani %1 nepomůže!'
    ];

    static objects = [
        'pocit, když člověk hoří',
        'rasizmus',
        ['vůně bezdomovce', 'vůni bezdomovce'],
        ['můj malý šulín', 'mého malého šulína'],
        ['modelka z&nbsp;reklamy na jogurty', 'modelku z&nbsp;reklamy na jogurty'],
        'mollový akord',
        'sraní na problémy rozvojových zemí',
        'strkání džbánku do zadku',
        ['soudně nařízená léčba', 'soudně nařízenou léčbu'],
        'větrný mlýn plný mrtvol',
        ['parta homosexuálů', 'partu homosexuálů'],
        'lízátko nadměrné velikosti',
        'dítě z Afriky',
        'ten pocit, když ho vrazíš mezi kozy různých velikostí',
        'ten pocit, když se ohneš a&nbsp;začneš vydělávat',
        ['tvrdě pracující cikán', 'tvrdě pracujícího cikána'],
        'oidipovský komplex',
        ['malý koník', 'malého koníka'],
        'šušeň z&nbsp;nosu',
        'žárlení na velikost cizích penisů',
        ['Václav Klaus', 'Václava Klause'],
        ['moje sada sexy faldů', 'mou sadu sexy faldů'],
        ['sada hrnců, co dědeček koupil na zájezdu', 'sadu hrnců, co dědeček koupil na zájezdu'],
        ['skupina Jehovistů', 'skupinu Jehovistů'],
        'zvracení naprázdno',
        ['včelka Mája', 'včelku Máju'],
        ['Darth Vader', 'Dartha Vadera'],
        'vanilkový pudink',
        ['rada od Jolandy z&nbsp;televize', 'radu od Jolandy z&nbsp;televize'],
        ['obří šiška salámu', 'obří šišku salámu'],
        ['indiánská stařena', 'indiánskou stařenu'],
        'vzorek zdarma',
        'estrogen',
        'erotické napětí',
        'hladomor',
        'zrzavý pubický chloupek',
        'dvanáct rozhněvaných mužů',
        'pět roztomilých sirotků',
        'kousek zabitého stopaře',
        'pytel kouzelných fazolí',
        'útisk nevinných',
        'vzepětí bezmocných',
        'stav mého vztahu',
        ['překompenzace komplexů', 'překompenzaci komplexů'],
        'malé učůrnutí',
        'kadění tam a&nbsp;zpátky',
        ['kulička ze špíny v&nbsp;uších', 'kuličku ze špíny v&nbsp;uších'],
        'hučení v kládě',
        ['samotný Ďábel', 'samotného Ďábla'],
        'The World of Warcraft',
        ['Jiří Paroubek', 'Jiřího Paroubka'],
        ['Andrej Babiš', 'Andreje Babiše'],
        ['pořádná frajeřina', 'pořádnou frajeřinu'],
        'pár obřích prsou',
        'depilační krém',
        ['osada Havranů', 'osadu Havranů'],
        'pár španělských rytmů',
        'chybějící varle Lance Armstronga',
        ['skupinka pedofilů', 'skupinku pedofilů'],
        ['papež', 'papeže'],
        'létající klubko sexy hadů',
        ['kardinál Duka', 'kardinála Duku'],
        'krmení Haliny Pawlowské',
        ['polštářová bitka v&nbsp;prádle', 'polštářovou bitku v&nbsp;prádle'],
        'útok na Polsko',
        'kybernetické vylepšení těla',
        'seznam obětí na civilním obyvatelstvu',
        'seznam volných pracovních míst',
        'ženský orgasmus',
        'pár čubiček',
        'oddíl skautů',
        'Osvětim',
        ['malůvka udělaná prstem', 'malůvku udělanou prstem'],
        'fusekle v&nbsp;sandálech',
        ['židovská obec', 'židovskou obec'],
        'tušení, že na tebe všichni kašlou',
        ['krev Ježíškova', 'krev Ježíšovu'],
        ['mrtvá rodina', 'mrtvou rodinu'],
        'jemné umění svádění',
        ['smrt způsobená průjmem', 'smrt způsobenou průjmem'],
        ['těžká vazba, hned za tebou', 'těžkou vazbu, hned za tebou'],
        'pytlík plný magnetů',
        'nevinný výstřik',
        'vinný střik',
        ['Zuzana Bubílková', 'Zuzanu Bubílkovou'],
        'zemědělství',
        ['soudkyně Barbara', 'soudkyni Barbaru'],
        'neočekávaný sex',
        'homosexualismus',
        ['Míša Jílková', 'Míšu Jílkovou'],
        'pár uslzených očí',
        'objektivní reportáž z&nbsp;Parlamentních listů',
        'nebojácný verš básníka Ošlejška',
        ['záře tisíce Sluncí', 'záři tisíce Sluncí'],
        ['amputace končetiny', 'amputaci končetiny'],
        'svrhnutí panny do vulkánu',
        'celý italský národ',
        'výbuch, co byl v&nbsp;pět',
        ['fajná lajna', 'fajnou lajnu'],
        ['likvidace důkazů', 'likvidaci důkazů'],
        'pár dětí na vodítku',
        'katapult',
        'sto milionů korun',
        ['nabíječ z&nbsp;Brna', 'nabíječe z&nbsp;Brna'],
        ['umírající Černohorec', 'umírajícího Černohorce'],
        'párek v&nbsp;rohlíku',
        ['Miloš Zeman', 'Miloše Zemana'],
        ['Leoš Mareš', 'Leoše Mareše'],
        ['Bible kralická', 'Bibli kralickou'],
        'pár pořádných koulí',
        ['neviditelná ruka trhu', 'neviditelnou ruku trhu'],
        'těhotenství mladistvých',
        'německé fekální porno',
        'potetovaný biceps',
        ['půlka mých vnitřních démonů', 'půlku mých vnitřních démonů'],
        'pár silných stehen',
        'stažené trenýrky',
        'hrozivý dluh',
        'Svaz pilotů kamikaze, kteří přežili',
        ['výchova dívek v&nbsp;Čechách', 'výchovu dívek v&nbsp;Čechách'],
        ['policejní brutalita', 'policejní brutalitu'],
        'koňské maso',
        'akce v&nbsp;sushi-baru',
        'protokol z&nbsp;vyšetření na psychiatrii',
        ['Lucie Bílá', 'Lucii Bílou'],
        ['ošoupaná kšiltovka', 'ošoupanou kšiltovku'],
        ['předstíraná emoce', 'předstíranou emoci'],
        'pytlík pervitinu',
        'tvarovací pás',
        'prstění',
        ['nepodařená oslava narozenin', 'nepodařenou oslavu narozenin'],
        'patriarchát',
        'střípek mé duše',
        ['putovní výstava masa', 'putovní výstavu masa'],
        'trvanlivý salám',
        ['eugenika', 'eugeniku'],
        'dokonalé manažerské rozhodnutí',
        ['major Zeman', 'majora Zemana'],
        ['cenzura internetu', 'cenzuru internetu'],
        ['akademik Wichterle vyprávějící sprosté vtipy', 'akademika Wichterle vyprávějícího sprosté vtipy'],
        ['muž předstírající orgasmus', 'muže předstírajícího orgasmus'],
        ['vůně ohně', 'vůni ohně'],
        'veřejný výsměch',
        'skalp Limonádového Joe',
        ['morbidní obezita', 'morbidní obezitu'],
        ['minimální doba trvanlivosti', 'minimální dobu trvanlivosti'],
        'kelímek jogurtu',
        'zaseknutí čelisti',
        ['Miroslav Kalousek', 'Miroslava Kalouska'],
        ['geneticky modifikovaná bojová želva', 'geneticky modifikovanou bojovou želvu'],
        'vlhký sen',
        ['krabička ukradených šmuků', 'krabičku ukradených šmuků'],
        ['kulka vystřelená do vzduchu při drbání kulek', 'kulku vystřelenou do vzduchu při drbání kulek'],
        'šukání s&nbsp;pandou',
        ['nekrofilie', 'nekrofilii'],
        'vykrádání hrobů',
        ['vybělená řiť', 'vybělenou řiť'],
        ['kněžna Libuše', 'kněžnu Libuši'],
        'mnohačetná bodná zranění',
        ['gentleman každým coulem', 'gentlemana každým coulem'],
        ['pistolník z Divokého západu', 'pistolníka z Divokého západu'],
        'legendární duo Eva &amp;&nbsp;Vašek',
        ['voda po holení Pitralon forte', 'vodu po holení Pitralon forte'],
        ['hodina strávená v&nbsp;posilovně', 'hodinu strávenou v&nbsp;posilovně'],
        'krátký šlofíček za volantem',
        'nůž s&nbsp;malovanou střenkou',
        ['drsná píseň o&nbsp;zabitém chlapovi z&nbsp;Koločavy a&nbsp;sudu od vína', 'drsnou píseň o&nbsp;zabitém chlapovi z&nbsp;Koločavy a&nbsp;sudu od vína'],
        'vybraný ročník krabicového vína',
        'nejpodařenější servis Sereny Williamsové',
        ['ústavní většina', 'ústavní většinu'],
        'slunce a hvězdy',
        'hvězdné nebe nade mnou a mravní zákon ve mně',
        'porušení základních lidských práv',
        'dělání ksichtů před zrcadlem',
        'komplikovaný nefungující přístroj',
        'kávovar čtvrté generace',
        ['duha klenoucí se přes celé nebe', 'duhu klenoucí se přes celé nebe'],
        ['třípětinová většina', 'třípětinovou většinu'],
        'teroristické komando Pošmourná sobota',
        'bičování hlava nehlava',
        ['želva chňapající po špičce penisu', 'želvu chňapající po špičce penisu'],
        'smrt při dopravní nehodě',
        ['holka krev a mlíko', 'holku krev a mlíko'],
        'krach na newyorské burze',
        ['nezvládnutá emoce', 'nezvládnutou emoci'],
        'takový vztek, až z&nbsp;něj má člověk erekci',
        'erotický tanec na ledě pro páry stejného pohlaví',
        'Kalašnikov',
        'lidské maso',
        'incest',
        ['nevymáchaná huba', 'nevymáchanou hubu'],
        ['nelétaví ptáci', 'nelétavé ptáky'],
        'nutkání udělat správnou věc',
        'upšouknutí, co nebylo jen upšouknutí',
        'skotačení',
        ['inkontinenční plena', 'inkontinenční plenu'],
        'vytahování se na děti',
        'ten moment, když vidíš prababičku nahou',
        ['útočící dravec', 'útočícího dravce'],
        ['prsatá kráska skákající přes švihadlo', 'prsatou krásku skákající přes švihadlo'],
        ['špatně ukrývaná erekce', 'špatně ukrývanou erekci'],
        ['nahota na prodej', 'nahotu na prodej'],
        ['silná paže jazzového hudebníka', 'silnou paži jazzového hudebníka'],
        'třapečky na bradavkách',
        ['facka přes celou hubu', 'facku přes celou hubu'],
        'půvaby Livie Klausové',
        'opar velikosti mexického dolaru',
        ['mongoloid jako asteroid', 'mongoloida jako asteroid'],
        'vzájemně zaručené zničení',
        ['pořádná extáze', 'pořádnou extázi'],
        ['slepá ulice', 'slepou ulici'],
        ['soudruh Stalin', 'soudruha Stalina'],
        ['laktační psychóza', 'laktační psychózu'],
        ['kůrovcová kalamita století', 'kůrovcovou kalamitu století'],
        'skutečný význam vánoc',
        'sebenenávist',
        'nádor na mozku',
        'mrtvé štěňátko pro mrtvé děťátko',
        ['hudba Michala Davida', 'hudbu Michala Davida'],
        ['termonukleární exploze', 'termonukleární explozi'],
        "kachny",
        'Ortel',
        ['Všemohoucí', 'Všemohoucího'],
        ['fracek s křivou hubou', 'fracka s křivou hubou'],
        ['erotická scéna z Káji Maříka', 'erotickou scénu z Káji Maříka'],
        'dětičky s tlamičkami zalitými betonem',
        ['sexuální představa pravicového sociologa', 'sexuální představu pravicového sociologa'],
        'americký sen',
        ['puberta', 'pubertu'],
        ['sladká, chladná pomsta', 'sladkou, chladnou pomstu'],
        'fixírování tety Kateřiny',
        'sladký kvítek orientu',
        ['Křemílek s Vochomůrkou', 'Křemílka s Vochomůrkou'],
        ['sentimentální boxer', 'sentimentálního boxera'],
        ['vysokohorská přirážka', 'vysokohorskou přirážku'],
        'rozestlané letiště',
        ['důkladná kontrola zavazadel', 'důkladnou kontrolu zavazadel'],
        ['rozesmátá parta puberťáků', 'rozesmátou partu puberťáků'],
        ['tryskomyška', 'tryskomyšku'],
        'oslňující laser',
        ['erektilní dysfunkce', 'erektilní dysfunkci'],
        ['rtíky jak slepičí prdelka', 'rtíky jak slepičí prdelku'],
        'selfíčko s Babišem',
        "flákanec a lívanec",
    ];

    phraseId;

    objects = [];

    constructor (phraseId, obj1, obj2) {
        this.phraseId = phraseId;
        this.objects.push(obj1);
        this.objects.push(obj2);
    }

    static getRandomPhraseIndex () {
        return Math.floor(Math.random() * this.phrases.length);
    };

    static getRandomObjectIndex () {
        return Math.floor(Math.random() * this.objects.length);
    };

    static firstToUpper (str) {
        return str[0].toUpperCase() + str.substr(1);
    };

    static decodeEntities (str) {
        var el = document.createElement("span");
        el.innerHTML = str;
        return el.innerText;
    }

    phraseReplace (match) {
        var word = Phrases.objects[this.objects.shift()];

        // First object or the 2nd?
        word = (Array.isArray(word) ? word[match.match(/2/) ? 1 : 0] : word)

        // 1st letter uppercase?
        if (match.match(/U/)) {
            word = Phrases.firstToUpper(word);
        }

        // Append comma?
        if (match.match(/C/) && word.indexOf(",") !== -1) {
            word = word + ",";
        }

        var dots = [];
        var word2 = Phrases.decodeEntities(word);
        for (var i in word2) {
            var c = word2.charCodeAt(i);
            dots.push(c == 32 || c == 160 ? word2[i] : ".");
        }
        return "<span class=\"covered\" data-word=\"" + word + "\">" + dots.join("") + "</span>";
    };

    getPhrase () {
        var t = this;
        return Phrases.phrases[this.phraseId].replace(
            /%(U|C|UC|CU){0,2}(1|2)(U|C|UC|CU){0,2}/g,
            function (match) {
                return t.phraseReplace.call(t, match);
            }
        );
    };
}
